version: '2'
services:
  mariadb:
    build: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
  recursive:
    build: recursive
    depends_on:
      - tld-server
  root-server:
    build: root-server
  tld-server:
    build: tld-server
    depends_on:
      - mariadb
      - root-server
  client:
    build: client
    depends_on:
      - recursive
